# General settings
title: Course material Catchment and Climate hydrology
author: Wageningen
#logo: images/TUDelft_logo_rgb.png
#copyright: Delft University of Technology

html:
  baseurl: "/Course-material-Catchment-and-Climate-hydrology"

# Execute notebooks when building
execute:
  execute_notebooks: auto

# START DRAFT
html:
  comments:
    hypothesis: true
# END DRAFT
html_static_path:
    - lec_slides
    
sphinx:
  local_extensions:
    apastyle: _ext/
    bracket_citation_style: _ext/
  extra_extensions:
    - sphinx_exercise
    - sphinx_copybutton
  
  config:
    bibtex_reference_style: author_year_round
    bibtex_default_style: myapastyle
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
bibtex_bibfiles: 
  - references.bib
