name: Deploy Jupyter Book

on:
  push:
    branches:
      - main
    paths:
      - "book/**"
      - ".github/workflows/**"
      - "requirements.txt"
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build book
      run: jupyter-book build book/

    - name: Deploy book
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: book/_build/html/
